### ISSUE TITLE
Telegram-bot development check-list

### ISSUE THREAD

**Issue by m0t9** [IU-Capstone-Project-2024/MoniDorm#10]
**High importance**
- [x] persistence of storage (with user data) via Redis / MongoDB
- [x] sending reports to backend
- [x] sending notifications anyhow to users
- [x] comments sending implementation
- [x] ADMIN_API_TOKEN separation
- [x] refactor ()
- [x] reimplement dialogue

**Average importance**
- [x] email confirmation code expiration

**Low importance**
- [ ] Russian language support

**Comment by CatOrLeader** [comment]
Пожалуйста, поделитесь результатами выполнения задачи и примерными сроками закрытия

**Comment by m0t9** [comment]
overall resolved
