### ISSUE TITLE
API Server: refactoring the API

### ISSUE THREAD

**Issue by CatOrLeader** [IU-Capstone-Project-2024/MoniDorm#22]
Need to implement next endpoints for better UX:

> А) добавь ендпоинт по добавлению комментария к репорту по его ID

It is also necessary to properly divide the token accessibility for the admin panel and the default report service

**Comment by m0t9** [comment]
Про токен аксесибилити не очень понял

**Comment by CatOrLeader** [comment]
#27
Закрываю. Пока что не добавлял разделение по токенам, так как это усложнит разработку других компонентов системы

Новый контракт: 
[contract.json](https://github.com/user-attachments/files/15931149/contract.json)
