### ISSUE TITLE
Traversal Communication: API --> TG Bot Server

### ISSUE THREAD

**Issue by CatOrLeader** [IU-Capstone-Project-2024/MoniDorm#23]
To create the foundation for the notifications, we need to discuss and create the system of communication between {API, TG Bot} in opposite to the default way. 
To be concise, it is necessary to call each other on the free time and discuss the key points, after this create subtasks and start to work on them

Please, specify the time you can attend an online meeting in comments

**Comment by m0t9** [comment]
го пятница вечер?) ну типа часов 8)

**Comment by CatOrLeader** [comment]
@m0t9 давай может завтра вечером? Чтобы сразу устаканить и работать в своем темпе

**Comment by m0t9** [comment]
я в казань еду( ну мб успеем ночью

**Comment by m0t9** [comment]
или в наушниках я в автобусе буду, мб тоже можно

**Comment by CatOrLeader** [comment]
Не, тогда давай в пятницу после работы, нужно выделить время, вопрос серьезный
Удобно будет в 17 30?

**Comment by m0t9** [comment]
должно быть да

**Comment by m0t9** [comment]
го лучше в 17:45

**Comment by CatOrLeader** [comment]
- [x] харашо

**Comment by CatOrLeader** [comment]
API-SERVER --> telegram bot server:

NotifyRequest:
```json
{[
  {
    "placement": "...",
    "category": "...",
    "failure_date": "...",
    "description": "..." (optional)
  },
  ...
]}
```

**Comment by CatOrLeader** [comment]
Вся нужная информация будет находится на соответствующей странице в вики
