### ISSUE TITLE
Notification Implementation

### ISSUE THREAD

**Issue by CatOrLeader** [IU-Capstone-Project-2024/MoniDorm#26]
Create proper UX/UI for subscribing to the places (or categories) via TG bot.
Design beautiful notification message
Buttons for sending, notif. subscribing, notif. unsubscribing

**Comment by cuprum-acid** [comment]
Please, provide more details and description

**Comment by CatOrLeader** [comment]
Attach possible button placement
![image](https://github.com/IU-Capstone-Project-2024/MoniDorm/assets/95234842/cbf17f06-28be-4341-af12-e2619b3b1ddb)

**Comment by m0t9** [comment]
implemented
