### ISSUE TITLE
Develop contracts for API

### ISSUE THREAD

**Issue by cuprum-acid** [IU-Capstone-Project-2024/MoniDorm#3]

**Comment by CatOrLeader** [comment]
Реализовал первую версию контракта для API Server

Прикладываю .json для дальнейшего анализа и оценки ниже: [contract-1.0.json](https://github.com/user-attachments/files/15778167/contract-1.0.json)

Для открытия использовать: https://editor-next.swagger.io/

Прошу оценить: @m0t9 @cuprum-acid

**Comment by CatOrLeader** [comment]
Архитектура утверждена для дальнейшей работы на данном этапе. Прикладываю ссылку на wiki с json-файлом:
https://github.com/IU-Capstone-Project-2024/MoniDorm/wiki/Architecture

**Comment by CatOrLeader** [comment]
Доработал контракт, изменения:

1) Добавлены поля при запросе и ответе репортов
2) Добавлены эндпоинты для менеджа репортов

[contract.json](https://github.com/user-attachments/files/15823098/contract.json)

Ожидаю ревью от: @m0t9

**Comment by CatOrLeader** [comment]
Close issue with the new version of api. All the other necessary stuff placed onto the Wiki
