### ISSUE TITLE
Failure Detector & Summarizer Service

### ISSUE THREAD

**Issue by CatOrLeader** [IU-Capstone-Project-2024/MoniDorm#34]
We need to implement the **single** python service, which can be described by the following checkpoints:

#### Inner Functionality

- [x] The service can access the data in PostgreSQL (near the API server). Why? To retrieve the data about reports and analyze it
- [x] Service scheduled to startup and scan database **one at X minutes** (to be chosen later)
- [x] Service should follow some 'guidelines' (self-created rules for detecting real failures)

#### Summarizer Functionality

- [x] The service can connect to the API of ChatGPT (or any other LLM); either use the internal python lib to summarize reports
- [x] The service has a predefined prompt to summarize the failure in the comments (or any additional information that can be provided from the API server)
- [x] The service can obtain the result of summarization and send it as a part of the message to the TG Bot

#### Detector Functionality

- [x] The service should be able to operate with the reports data (PostgreSQL), store it in runtime
- [x] The service has the ability to detect the failure confirmation from the bunch of reports, given by several common criteria
- [x] The service has flexible configuration to change the detection functionality without changing the code
- [x] The service should send message to the bot with failure notification. You can send several messages at one epoch (moment, when the service started to analyze), but not in one HTTP request

**Comment by CatOrLeader** [comment]
Пожалуйста, поделитесь результатами выполнения задачи и примерными сроками закрытия

**Comment by CatOrLeader** [comment]
Attach the openAPI specification for the telegram web server. The request format should be strictly followed by the failure detector service:
[openapi3_0.json](https://github.com/user-attachments/files/15992027/openapi3_0.json)

**Comment by m0t9** [comment]
resolved
