### ISSUE TITLE
Report Week #4

### ISSUE THREAD

**Issue by CatOrLeader** [IU-Capstone-Project-2024/MoniDorm#35]
## Important Points

- [x] **External Feedback**: Try to find a group of people (fellow students or friends) who will agree to give you an honest feedback on your product
- [x] **Testing**: The report primarily focuses on the software development section. Analyze and describe the tests we have in our project
- [x] **Iteration**: We need to clearly see the progress we have made compared to previous weeks. It would be helpful to review the steps we took during these four weeks and our future plans in order to refine them

### Conclusions & Next Steps

**Comment by CatOrLeader** [comment]
Пожалуйста, поделитесь результатами выполнения задачи и примерными сроками закрытия

**Comment by cuprum-acid** [comment]
Please, provide links to deployed applications 🙏

**Comment by CatOrLeader** [comment]
> Please, provide links to deployed applications 🙏

Please, create new merge request to the capstone-project-PR repo
