### ISSUE TITLE
Database design

### ISSUE THREAD

**Issue by cuprum-acid** [IU-Capstone-Project-2024/MoniDorm#4]

**Comment by CatOrLeader** [comment]
База данных была успешно интегрирована в рабочий процесс API-Сервера. Далее представлена модель данных, которую планируется поддерживать на этапе MVP: 

```sql
CREATE TABLE IF NOT EXISTS report(
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    category varchar(128) NOT NULL,
    placement varchar(128) NOT NULL,
    failure_date TIMESTAMP WITH TIME ZONE,
    proceeded_date TIMESTAMP WITH TIME ZONE,
    owner_email varchar(128),
    is_confirmed_by_analysis BOOLEAN NOT NULL,
    is_confirmed_by_admin BOOLEAN NOT NULL,
    is_resolved_by_user BOOLEAN NOT NULL,
    is_resolved_by_admin BOOLEAN NOT NULL,
    description varchar(256)
);
```

Поток запуска docker-compose:

1) Поднимается контейнер PostgreSQL с портом 5432 наружу и заранее заданными переменными окружения (через .env файл)
2) После того, как контейнер базы успешно поднят, поднимается контейнер Liquibase, который накатывает миграции (схему данных) в PostgreSQL
3) Контейнер миграций успешно завершает работу

Для подробностей обратиться к #18
