### ISSUE TITLE
Beginning development of a telegram bot

### ISSUE THREAD

**Issue by cuprum-acid** [IU-Capstone-Project-2024/MoniDorm#5]
Come up with an initial interface for the bot

**Comment by m0t9** [comment]
Бим-бим бам-бам
<img width="1037" alt="image" src="https://github.com/IU-Capstone-Project-2024/MoniDorm/assets/60100612/1cb29fe1-5b5f-44e5-ba37-4b752d88551d">
![telegram-cloud-document-2-5424784874441558253](https://github.com/IU-Capstone-Project-2024/MoniDorm/assets/60100612/9c860586-acf4-4492-891f-a4620c997f62)
