### ISSUE TITLE
Resolving Issue with the DateTime format

### ISSUE THREAD

**Issue by CatOrLeader** [IU-Capstone-Project-2024/MoniDorm#7]
Solve the problem connected to the different timezones between users. The necessary steps:

1) Understand the datetime format of telegram message's metadata
2) Analyze the found evidence
3) Solve the problem with the timezones, synchronize work of the backend system between different services

**Comment by CatOrLeader** [comment]
@m0t9 
Please, provide the valuable information (add screenshots) with the date/time saved on the API server from the request. Also, please add the information about the time that returned to the bot (under any endpoint)

**Comment by m0t9** [comment]
- Я не использую метадату телеги, а просто беру локальное время и кидаю его тебе. Кажется, как раз проблема в этом. Нужно просто utc кидать тебе. И вроде разница как раз 3 часа

**Comment by CatOrLeader** [comment]
Тогда пожалуйста, уточни этот момент и скажи, нужна ли доработка со стороны апи

**Comment by m0t9** [comment]
решил, пока не запушил но нормик крч. У себя кидаю utc isoformat
